export const actionTypes = {
    FETCH_NEWS_REQUEST: 'FETCH_NEWS_REQUEST',
    FETCH_NEWS_RESPONSE: 'FETCH_NEWS_RESPONSE',

    FETCH_ALL_NEWS_REQUEST: 'FETCH_ALL_NEWS_REQUEST',
    FETCH_ALL_NEWS_RESPONSE: 'FETCH_ALL_NEWS_RESPONSE'
}